In [1]:
# Lucky Choudhary
# Writing all queries such as Top 5 Stores by Total Sales, Top 5 Departments by Sales, Holiday vs Non-Holiday Sales Analysis, Monthly Sales Trend, 
# Sales by Store Type, Stores with Highest Discount Dependency, Best Performing Stores (Adjusted Performance), Quarterly Sales Analysis and Sales vs Store Efficiency 
import sqlite3
import pandas as pd

conn = sqlite3.connect("../database/walmart.db")

## Top 5 Stores by Total Sales

This query identifies the top-performing stores based on total sales.

Business Goal:
To understand which stores generate the highest revenue and contribute most to overall performance.

In [2]:
query = """
SELECT Store, SUM(Weekly_Sales) AS total_sales
FROM sales
GROUP BY Store
ORDER BY total_sales DESC
LIMIT 5;
"""
pd.read_sql(query, conn)

   Store   total_sales
0     20  3.013978e+08
1      4  2.995440e+08
2     14  2.889999e+08
3     13  2.865177e+08
4      2  2.753824e+08

## Top 5 Departments by Sales

This query highlights the departments with the highest total sales.

Business Goal:
To identify which product categories drive the most revenue.

In [3]:
query = """
SELECT Dept, SUM(Weekly_Sales) AS total_sales
FROM sales
GROUP BY Dept
ORDER BY total_sales DESC
LIMIT 5;
"""
pd.read_sql(query, conn)

   Dept   total_sales
0    92  4.839433e+08
1    95  4.493202e+08
2    38  3.931181e+08
3    72  3.057252e+08
4    90  2.910685e+08

## Holiday vs Non-Holiday Sales Analysis

This query compares average sales during holiday and non-holiday periods.

Business Goal:
To analyze the effect of holidays on customer purchasing behavior.

In [4]:
query = """
SELECT IsHoliday, AVG(Weekly_Sales) AS avg_sales
FROM sales
GROUP BY IsHoliday;
"""
pd.read_sql(query, conn)

   IsHoliday     avg_sales
0          0  15901.445069
1          1  17035.823187

## Monthly Sales Trend

This query analyzes average sales across different months.

Business Goal:
To identify seasonal patterns and peak sales months.

In [5]:
query = """
SELECT Month, AVG(Weekly_Sales) AS avg_sales
FROM sales
GROUP BY Month
ORDER BY Month;
"""
pd.read_sql(query, conn)

    Month     avg_sales
0       1  14126.075111
1       2  16008.779217
2       3  15416.657597
3       4  15650.338357
4       5  15776.337202
5       6  16326.137002
6       7  15861.419650
7       8  16062.516933
8       9  15095.886154
9      10  15243.855576
10     11  17491.031424
11     12  19355.702141

## Sales by Store Type

This query compares average sales across different store types.

Business Goal:
To evaluate how store classification impacts performance.

In [6]:
query = """
SELECT Type, AVG(Weekly_Sales) AS avg_sales
FROM sales
GROUP BY Type;
"""
pd.read_sql(query, conn)

  Type     avg_sales
0    A  20099.568043
1    B  12237.075977
2    C   9519.532538

## Stores with Highest Discount Dependency

This query identifies stores that rely heavily on discounts.

Business Goal:
To understand how much stores depend on promotions to drive sales.

In [7]:
query = """
SELECT Store, AVG(Discount_Ratio) AS avg_discount
FROM sales
GROUP BY Store
ORDER BY avg_discount DESC
LIMIT 5;
"""
pd.read_sql(query, conn)

   Store  avg_discount
0     31   1423.165339
1     24    874.193719
2     39    510.406697
3      1    490.571730
4      8    429.123362

## Best Performing Stores (Adjusted Performance)

This query ranks stores based on performance score, which accounts for discount impact.

Business Goal:
To identify stores that perform well without heavy reliance on discounts.

In [8]:
query = """
SELECT Store, AVG(Performance_Score) AS performance
FROM sales
GROUP BY Store
ORDER BY performance DESC
LIMIT 5;
"""
pd.read_sql(query, conn)

   Store   performance
0      4  19462.700680
1     14  18758.392844
2     20  18559.832489
3     10  16863.652435
4      2  16860.622240

## Quarterly Sales Analysis

This query shows total sales across different quarters.

Business Goal:
To analyze seasonal trends and business cycles.

In [9]:
query = """
SELECT Quarter, SUM(Weekly_Sales) AS total_sales
FROM sales
GROUP BY Quarter
ORDER BY Quarter;
"""
pd.read_sql(query, conn)

   Quarter   total_sales
0        1  1.494112e+09
1        2  1.826615e+09
2        3  1.841852e+09
3        4  1.574639e+09

## Sales vs Store Efficiency

This query compares total sales with sales efficiency (sales per store size).

Business Goal:
To identify whether high sales come from efficiency or just large store size.

In [10]:
query = """
SELECT Store,
       AVG(Weekly_Sales) AS sales,
       AVG(Sales_per_Size) AS efficiency
FROM sales
GROUP BY Store
ORDER BY sales DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

   Store         sales  efficiency
0     20  29508.301592    0.144832
1      4  29161.210415    0.141653
2     14  28784.851727    0.143281
3     13  27355.136891    0.124556
4      2  26898.070031    0.132957
5     10  26332.303819    0.208141
6     27  24826.984536    0.121591
7      6  21913.243624    0.108211
8      1  21710.543621    0.143479
9     39  21000.763562    0.114067